image: docker:git

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  GITLAB_REGISTRY: registry.gitlab.com

  # common tags so ArgoCD can detect updated images
  # - staging: branch name + short SHA
  # - production: CI tag + short SHA
  STAGING_TAG: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
  PRODUCTION_TAG: "$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"

.docker_login:
  before_script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"

.build_image_staging:
  stage: build
  extends: .docker_login
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

.build_image_production:
  stage: build
  extends: .docker_login
  rules:
    - if: '$CI_COMMIT_TAG != null'

build_backend_staging:
  extends: .build_image_staging
  script:
    - export IMAGE_BASE="$GITLAB_REGISTRY/$CI_PROJECT_PATH/backend"
    - export IMAGE_TAG="staging-$STAGING_TAG"
    - docker build -t "$IMAGE_BASE:$IMAGE_TAG" -f Dockerfile .
    - docker push "$IMAGE_BASE:$IMAGE_TAG"

build_frontend_staging:
  extends: .build_image_staging
  script:
    - export IMAGE_BASE="$GITLAB_REGISTRY/$CI_PROJECT_PATH/frontend"
    - export IMAGE_TAG="staging-$STAGING_TAG"
    - docker build -t "$IMAGE_BASE:$IMAGE_TAG" -f frontend/Dockerfile ./frontend
    - docker push "$IMAGE_BASE:$IMAGE_TAG"

build_markitdown_staging:
  extends: .build_image_staging
  script:
    - export IMAGE_BASE="$GITLAB_REGISTRY/$CI_PROJECT_PATH/markitdown"
    - export IMAGE_TAG="staging-$STAGING_TAG"
    - docker build -t "$IMAGE_BASE:$IMAGE_TAG" -f services/markitdown_api/Dockerfile ./services/markitdown_api
    - docker push "$IMAGE_BASE:$IMAGE_TAG"

build_vectorchat_light_staging:
  extends: .build_image_staging
  script:
    - export IMAGE_BASE="$GITLAB_REGISTRY/$CI_PROJECT_PATH/vectorchat-light"
    - export IMAGE_TAG="staging-$STAGING_TAG"
    - docker build -t "$IMAGE_BASE:$IMAGE_TAG" --target production -f vectorchat-light/Dockerfile ./vectorchat-light
    - docker push "$IMAGE_BASE:$IMAGE_TAG"

build_crawl_scheduler_staging:
  extends: .build_image_staging
  script:
    - export IMAGE_BASE="$GITLAB_REGISTRY/$CI_PROJECT_PATH/crawl-scheduler"
    - export IMAGE_TAG="staging-$STAGING_TAG"
    - docker build -t "$IMAGE_BASE:$IMAGE_TAG" -f Dockerfile .
    - docker push "$IMAGE_BASE:$IMAGE_TAG"

build_backend_production:
  extends: .build_image_production
  script:
    - export IMAGE_BASE="$GITLAB_REGISTRY/$CI_PROJECT_PATH/backend"
    - export IMAGE_TAG="latest-$PRODUCTION_TAG"
    - docker build -t "$IMAGE_BASE:$IMAGE_TAG" -f Dockerfile .
    - docker push "$IMAGE_BASE:$IMAGE_TAG"

build_frontend_production:
  extends: .build_image_production
  script:
    - export IMAGE_BASE="$GITLAB_REGISTRY/$CI_PROJECT_PATH/frontend"
    - export IMAGE_TAG="latest-$PRODUCTION_TAG"
    - docker build -t "$IMAGE_BASE:$IMAGE_TAG" -f frontend/Dockerfile ./frontend
    - docker push "$IMAGE_BASE:$IMAGE_TAG"

build_markitdown_production:
  extends: .build_image_production
  script:
    - export IMAGE_BASE="$GITLAB_REGISTRY/$CI_PROJECT_PATH/markitdown"
    - export IMAGE_TAG="latest-$PRODUCTION_TAG"
    - docker build -t "$IMAGE_BASE:$IMAGE_TAG" -f services/markitdown_api/Dockerfile ./services/markitdown_api
    - docker push "$IMAGE_BASE:$IMAGE_TAG"

build_vectorchat_light_production:
  extends: .build_image_production
  script:
    - export IMAGE_BASE="$GITLAB_REGISTRY/$CI_PROJECT_PATH/vectorchat-light"
    - export IMAGE_TAG="latest-$PRODUCTION_TAG"
    - docker build -t "$IMAGE_BASE:$IMAGE_TAG" --target production -f vectorchat-light/Dockerfile ./vectorchat-light
    - docker push "$IMAGE_BASE:$IMAGE_TAG"

build_crawl_scheduler_production:
  extends: .build_image_production
  script:
    - export IMAGE_BASE="$GITLAB_REGISTRY/$CI_PROJECT_PATH/crawl-scheduler"
    - export IMAGE_TAG="latest-$PRODUCTION_TAG"
    - docker build -t "$IMAGE_BASE:$IMAGE_TAG" -f Dockerfile .
    - docker push "$IMAGE_BASE:$IMAGE_TAG"

deploy_staging:
  stage: deploy
  image: alpine:latest
  environment:
    name: staging
    url: https://vectorchat.staging.devs-group.com/
  when: on_success
  before_script:
    - apk add curl
  script:
    - |
      # I know but im still doing this.
      curl -X GET "https://sloth.podseidon.io/v1/hook/1" -H "X-Access-Token: pi8emapx8x8q"
  only:
    - main

deploy_production:
  stage: deploy
  image: alpine:latest
  environment:
    name: production
    url: https://vectorchat.devs-group.com/
  when: on_success
  before_script:
    - apk add curl
  script:
    - |
      # I know but im still doing this.
      curl -X GET "https://sloth.podseidon.io/v1/hook/2" -H "X-Access-Token: xvj7lbllf4cq"
  only:
    - tags
