image: docker:git

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  GITLAB_REGISTRY: registry.gitlab.com

build_backend_staging:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - export CONTAINER_PATH=$GITLAB_REGISTRY/$CI_PROJECT_PATH/backend:staging
    - docker build -t $CONTAINER_PATH -f Dockerfile .
    - docker push $CONTAINER_PATH
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

build_frontend_staging:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - export CONTAINER_PATH=$GITLAB_REGISTRY/$CI_PROJECT_PATH/frontend:staging
    - docker build -t $CONTAINER_PATH -f frontend/Dockerfile ./frontend
    - docker push $CONTAINER_PATH
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

build_markitdown_staging:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - export CONTAINER_PATH=$GITLAB_REGISTRY/$CI_PROJECT_PATH/markitdown:staging
    - docker build -t $CONTAINER_PATH -f services/markitdown_api/Dockerfile ./services/markitdown_api
    - docker push $CONTAINER_PATH
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

build_vectorchat_light_staging:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - export CONTAINER_PATH=$GITLAB_REGISTRY/$CI_PROJECT_PATH/vectorchat-light:staging
    - docker build -t $CONTAINER_PATH --target production -f vectorchat-light/Dockerfile ./vectorchat-light
    - docker push $CONTAINER_PATH
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

build_backend_production:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - export CONTAINER_PATH=$GITLAB_REGISTRY/$CI_PROJECT_PATH/backend:latest
    - docker build -t $CONTAINER_PATH -f Dockerfile .
    - docker push $CONTAINER_PATH
  rules:
    - if: "$CI_COMMIT_TAG != null"

build_frontend_production:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - export CONTAINER_PATH=$GITLAB_REGISTRY/$CI_PROJECT_PATH/frontend:latest
    - docker build -t $CONTAINER_PATH -f frontend/Dockerfile ./frontend
    - docker push $CONTAINER_PATH
  rules:
    - if: "$CI_COMMIT_TAG != null"

build_markitdown_production:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - export CONTAINER_PATH=$GITLAB_REGISTRY/$CI_PROJECT_PATH/markitdown:latest
    - docker build -t $CONTAINER_PATH -f services/markitdown_api/Dockerfile ./services/markitdown_api
    - docker push $CONTAINER_PATH
  rules:
    - if: "$CI_COMMIT_TAG != null"

build_vectorchat_light_production:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - export CONTAINER_PATH=$GITLAB_REGISTRY/$CI_PROJECT_PATH/vectorchat-light:latest
    - docker build -t $CONTAINER_PATH --target production -f vectorchat-light/Dockerfile ./vectorchat-light
    - docker push $CONTAINER_PATH
  rules:
    - if: "$CI_COMMIT_TAG != null"

deploy_staging:
  stage: deploy
  image: alpine:latest
  environment:
    name: staging
    url: https://vectorchat.staging.devs-group.com/
  when: on_success
  before_script:
    - apk add curl
  script:
    - |
      # I know but im still doing this.
      curl -X GET "https://sloth.podseidon.io/v1/hook/1" -H "X-Access-Token: pi8emapx8x8q"
  only:
    - main

deploy_production:
  stage: deploy
  image: alpine:latest
  environment:
    name: production
    url: https://vectorchat.devs-group.com/
  when: on_success
  before_script:
    - apk add curl
  script:
    - |
      # I know but im still doing this.
      curl -X GET "https://sloth.podseidon.io/v1/hook/2" -H "X-Access-Token: xvj7lbllf4cq"
  only:
    - tags
