services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: vectorchat-frontend
    environment:
      - API_BASE_URL=http://localhost:8080
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    networks:
      - vectorchat-network
    depends_on:
      - app

  vectorchat-light:
    build:
      context: ./vectorchat-light
      dockerfile: Dockerfile
      target: development
    container_name: vectorchat-light
    environment:
      - API_BASE_URL=http://localhost:8080
    ports:
      - "3100:3000"
    volumes:
      - ./vectorchat-light:/app
      - /app/node_modules
      - /app/.nuxt
    networks:
      - vectorchat-network
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: vectorchat-app
    command: air
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:postgres@postgres:5432/vectordb?sslmode=disable
      - OPENAI_API_KEY
      - CRAWLER_API_URL=http://crawl4ai:11235
      - MARKITDOWN_API_URL=http://markitdown:8000
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ./uploads:/root/uploads
      - ./.air.toml:/app/.air.toml
    networks:
      - vectorchat-network
    env_file:
      - .env

  postgres:
    image: pgvector/pgvector:pg14
    container_name: vectorchat-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vectordb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vectorchat-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vectorchat-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - ./pgadmin4/pgpass:/pgadmin4/pgpass
    depends_on:
      - postgres
    networks:
      - vectorchat-network

  markitdown:
    build:
      context: .
      dockerfile: services/markitdown_api/Dockerfile
    container_name: vectorchat-markitdown
    ports:
      - "8000:8000"
    networks:
      - vectorchat-network

  crawl4ai:
    image: unclecode/crawl4ai:latest
    container_name: vectorchat-crawl4ai
    ports:
      - "11235:11235"
    networks:
      - vectorchat-network

networks:
  vectorchat-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
