model_list:
  - model_name: chat-default
    litellm_params:
      model: gpt-5.1-chat-latest
  - model_name: gpt-5-mini
    litellm_params:
      model: gpt-5-mini
  - model_name: gemini-2.5-pro
    litellm_params:
      model: google/gemini-2.5-pro-exp-03-25
  - model_name: gemini-default
    litellm_params:
      model: google/gemini-2.0-flash-lite

router_settings:
  num_retries: 2
  timeout: 60

litellm_settings:
  drop_params: true
  cache: false
